# Generated by Django 4.2.6 on 2023-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_manufacturer_car_transmition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Luxury', 'Luxury'), ('Economy', 'Economy'), ('Executive', 'Executive')], max_length=200, null=True),
        ),
    ]
