# Generated by Django 4.2.6 on 2023-11-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.manufacturer'),
        ),
    ]
