# Generated by Django 4.2.6 on 2023-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_manufacturer_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
