# Generated by Django 4.2.6 on 2023-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='outcityprice',
            field=models.IntegerField(null=True),
        ),
    ]
