# Generated by Django 4.2.6 on 2023-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
